### ISSUE TITLE
Create Task and To-do Backend and Frontend Models

### ISSUE THREAD

**Issue by emmalynfoster** [emmalynfoster/task-manager#3]
This feature will create the pydantic models for transferring data between service layers. 

## Why? 
This will allow us to transfer information about each task and to-do between the database and frontend services through APIs. 

## Acceptance Criteria 
- [ ] `Task` pydantic model with id, title, description, due date, complete (boolean), and category in backend
- [ ] Category must be set to type of enum created for entities 
- [ ] `To-do` pydantic model with id and text field in the backend
- [ ] Corresponding frontend models for `Task` and `To-do`
