### ISSUE TITLE
Create To-do Object and Services

### ISSUE THREAD

**Issue by emmalynfoster** [emmalynfoster/task-manager#5]
This feature will act as the To-do table for entries into our database along with the services for interacting with the To-do list from the frontend. 

## Why? 
This will allow the user to interact with their to-dos. 

## Acceptance Criteria
- [ ] To-do object with id as primary key and text field

Services: 
- [ ] Get all to-do items
- [ ] Get a to-do item by id
- [ ] Create a to-do item
- [ ] Delete a to-do item
