### ISSUE TITLE
Create To-do Widget to Display To-do Text List Inside

### ISSUE THREAD

**Issue by emmalynfoster** [emmalynfoster/task-manager#8]
This feature will display the To-do widget inside the main landing page, including a list of to-do entries. 

## Why? 
This will fulfill object requirements and allow the user to create more general notes if they do not apply to the given categories. 

## Acceptance Criteria
- [ ] Singular to-do widget component to display on page
- [ ] Grabs all to-do entries and displays them in a list form
- [ ] Similar CSS to Task Widgets
